config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  root to: 'home#index'
  get :dashboard, to: 'home#dashboard'

  resources :payments do
    resources :transfers
  end

  resources :groups do
  	member do
      get :new_user
      post :add_user
      post :remove_user
    end
  end

  resource :bill_splitting, controller: 'bill_splitting'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, :all
  end
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users
  validates :name, presence: true
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :receiver, class_name: "User", foreign_key: :receiver_id
  belongs_to :sender, class_name: "User", foreign_key: :sender_id
  has_many :transfers

  validates :sender, :receiver, :amount, :description, :due_date, presence: true
  validate :not_sending_to_self

  scope :unpaid, -> { where.not(status: 'paid') }
  scope :paid, -> { where(status: 'paid') }

  before_save :update_status
  after_touch :save

  def amount_paid
    transfers.sum(:amount)
  end

  def amount_unpaid
    amount - amount_paid
  end

private
  def update_status
    self.status = case amount_paid
    when 0
      :unpaid
    when amount
      :paid
    else
      :partially_paid
    end
  end

  def not_sending_to_self
    if sender == receiver
      self.errors.add(:receiver, 'cannot send to self')
    end
  end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/transfer.rb
class Transfer < ActiveRecord::Base
  belongs_to :payment, touch: true
  validates :payment, :amount, :transfer_method, presence: true
  validate :no_overpay, on: :create
  validates :amount, numericality: {greater_than: 0}

private
  def no_overpay
    if payment.amount_unpaid < amount
      self.errors.add(:amount, "is too large. Cannot pay more than #{payment.amount_unpaid}")
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :groups
  has_many :sent_payments, class_name: "Payment", foreign_key: :sender_id
  has_many :received_payments, class_name: "Payment", foreign_key: :receiver_id

  ratyrate_rater
  ratyrate_rateable 'Overall'

  def user_balance_with(user)
  	other_sent = self.sent_payments.where(receiver_id:user.id).sum(:amount)
  	other_rec = self.received_payments.where(sender_id:user.id).sum(:amount)
  	balance = other_rec - other_sent
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  respond_to :html
  rescue_from CanCan::AccessDenied do
    flash[:danger] = 'You are not authorized to view this page'
    redirect_to root_path
  end
  layout :layout_by_resource

  before_filter :update_sanitized_params, if: :devise_controller?

protected
  def layout_by_resource
    if devise_controller?
      "login"
    elsif params[:controller] == 'home'
      "application"
    else
      "dashboard"
    end
  end

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
  end
end

app/controllers/bill_splitting_controller.rb
class BillSplittingController < ApplicationController

  def new
  end

  def create
    @group = current_user.groups.find(params[:group_id])
    balance = params[:amount].to_f / @group.users.size

    @group.users.each do |user|
      next if user == current_user
      user.sent_payments.create!(payment_params) do |payment|
        payment.amount = balance
        payment.receiver = current_user
      end
    end
    flash[:success] = "Successfully split bill"
    redirect_to :payments
  end

private
  def payment_params
    params.require(:payment).permit(:description, :due_date)
  end
end

app/controllers/groups_controller.rb
=begin
  TODO
  add redircts for success
=end

class GroupsController < ApplicationController
  load_and_authorize_resource :group

  def new_user
    @user = User.new
  end

  def index
    @groups = current_user.groups
  end

  def new
  end

  def create
    @group = current_user.groups.create(group_params)
    if @group.valid?
      flash[:success] = 'Group created successfully'
      redirect_to :groups
    else
      flash[:danger] = 'Group failed to create'
      render(:new)
    end
  end

  def show
  end

  def add_user
    @group.users << User.find(params[:user_id])
    redirect_to @group
  end

  def remove_user
    @user = User.find(params[:user_id])
    @group = user.groups.find(params[:group_id])
    if group
      user.groups.delete(group)
    else
      flash[:danger] = 'Could not remove user from group'
      render(:new)
    end
  end
private
  def group_params
    params.require(:group).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout false
  def index
    if current_user
      if current_user.groups.any?
        redirect_to :payments
      else
        redirect_to new_group_path
      end
    end
  end

  def dashboard
    render :dashboard, layout: 'dashboard'
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  load_and_authorize_resource :payment

  def index
    @sent_payments = current_user.sent_payments
    @received_payments = current_user.received_payments
  end

  def new
    @payment.assign_attributes((payment_params rescue {}))
  end

  def create
    @payment.save
    respond_with @payment
  end

  def show
  end

private
  def payment_params
    params.require(:payment).permit(:description, :amount, :receiver_id, :sender_id, :due_date)
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  load_and_authorize_resource :payment
  load_and_authorize_resource :transfer, through: :payment

  def new
  end

  def create
    if @transfer.save
      respond_with @payment
    else
      respond_with @payment, @transfer
    end
  end

private
  def transfer_params
    params.require(:transfer).permit(:amount, :transfer_method)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class_for(obj)
    if url_for(obj) == request.path
      'active'
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
  def label_status_class(status)
    case status
    when 'unpaid'
      'label-danger'
    when 'partially_paid'
      'label-warning'
    when 'paid'
      'label-success'
    end
  end
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/views/bill_splitting/new.html.erb
<div class="col-md-6">
  <h1>Split a bill</h1>
  <%= form_tag :bill_splitting do %>
    <fieldset class="form-group">
      <%= label_tag :group %>
      <%= select_tag :group_id, options_from_collection_for_select(Group.all, "id", "name"), class: 'form-control' %>
    </fieldset>
    <fieldset class="form-group">
      <%= label_tag :amount %>
      <div class="input-group">
        <div class="input-group-addon">$</div>
        <%= number_field_tag :amount, nil, class: 'form-control', step: '0.01' %>
      </div>
    </fieldset>
    <fieldset class="form-group">
      <%= label_tag :description %>
      <%= text_field_tag 'payment[description]', nil, class: 'form-control', placeholder: "Hydro bill" %>
    </fieldset>
    <fieldset class="form-group">
      <%= label_tag :due_date %>
      <%= date_field_tag 'payment[due_date]', nil, class: 'form-control', value: 1.week.from_now.strftime('%Y-%m-%d')%>
    </fieldset>
    <fieldset class="form-group">
      <%= submit_tag 'Submit bill', class: 'btn btn-primary' %>
    </fieldset>
  <% end %>
</div>

app/views/groups/index.html.erb
<h1>Your groups <%= link_to '+ Group', new_group_path, class: 'btn btn-primary' %></h1>
<ul>
  <% @groups.each do |group| %>
    <li style="list-style-type: none"><%= link_to group.name, group %></li>
    <hr style = "border-top: 1px solid #ccc">
  <% end %>
</ul>

app/views/groups/new.html.erb
<h1>Create a group</h1>
<div class="col-md-6">
  <%= form_for @group do |f| %>
    <%= render 'shared/error_messages', obj: @group %>

    <fieldset class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </fieldset>

    <fieldset class="form-group">
      <%= f.submit 'Create', class: 'btn btn-primary' %>
    </fieldset>
  <% end %>
</div>

app/views/groups/new_user.html.erb
<h1>Add user to <%= @group.name %></h1>
<%= form_tag add_user_group_path(@group) do %>
  <fieldset class="form-group">
    <%= select_tag :user_id, options_from_collection_for_select(User.all, "id", "name"), {include_blank: "Choose", class: 'form-control'} %>
  </fieldset>
  <fieldset class="form-group">
    <%= submit_tag 'Add', class: 'btn btn-primary' %>
  </fieldset>
<% end %>

app/views/groups/show.html.erb
<div class="col-md-6">
  <h1><%= @group.name %> Group</h1>
  <h3>Members <%= link_to '+ User', new_user_group_path(@group), class: 'btn btn-primary pull-right' %></h3>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Rating</th>
      </tr>
    </thead>
    <tbody>
      <% @group.users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= rating_for user, "Overall" %></td>
        </tr>
      <% end %>

      <!-- Style for user ratings on the 'show group' page -->
      <div class="rating">
        <% if current_user %>
          Overall: <%= rating_for current_user, "Overall", disable_after_rate: false, cancel_hint: 'Cancel this vote!' %>
        <% end %>
      </div>
    </tbody>
  </table>
</div>

app/views/home/dashboard.html.erb
<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Dashboard <small>Statistics Overview</small>
        </h1>
        <ol class="breadcrumb">
            <li class="active">
                <i class="fa fa-dashboard"></i> Dashboard
            </li>
        </ol>
    </div>
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <div class="alert alert-info alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <i class="fa fa-info-circle"></i>  <strong>Like SB Admin?</strong> Try out <a href="http://startbootstrap.com/template-overviews/sb-admin-2" class="alert-link">SB Admin 2</a> for additional features!
        </div>
    </div>
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-comments fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">26</div>
                        <div>New Comments!</div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left">View Details</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-green">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-tasks fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">12</div>
                        <div>New Tasks!</div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left">View Details</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-yellow">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-shopping-cart fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">124</div>
                        <div>New Orders!</div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left">View Details</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-red">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-support fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">13</div>
                        <div>Support Tickets!</div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left">View Details</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i> Area Chart</h3>
            </div>
            <div class="panel-body">
                <div id="morris-area-chart"></div>
            </div>
        </div>
    </div>
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-long-arrow-right fa-fw"></i> Donut Chart</h3>
            </div>
            <div class="panel-body">
                <div id="morris-donut-chart"></div>
                <div class="text-right">
                    <a href="#">View Details <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-clock-o fa-fw"></i> Tasks Panel</h3>
            </div>
            <div class="panel-body">
                <div class="list-group">
                    <a href="#" class="list-group-item">
                        <span class="badge">just now</span>
                        <i class="fa fa-fw fa-calendar"></i> Calendar updated
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">4 minutes ago</span>
                        <i class="fa fa-fw fa-comment"></i> Commented on a post
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">23 minutes ago</span>
                        <i class="fa fa-fw fa-truck"></i> Order 392 shipped
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">46 minutes ago</span>
                        <i class="fa fa-fw fa-money"></i> Invoice 653 has been paid
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">1 hour ago</span>
                        <i class="fa fa-fw fa-user"></i> A new user has been added
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">2 hours ago</span>
                        <i class="fa fa-fw fa-check"></i> Completed task: "pick up dry cleaning"
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">yesterday</span>
                        <i class="fa fa-fw fa-globe"></i> Saved the world
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">two days ago</span>
                        <i class="fa fa-fw fa-check"></i> Completed task: "fix error on sales page"
                    </a>
                </div>
                <div class="text-right">
                    <a href="#">View All Activity <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-money fa-fw"></i> Transactions Panel</h3>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-striped">
                        <thead>
                            <tr>
                                <th>Order #</th>
                                <th>Order Date</th>
                                <th>Order Time</th>
                                <th>Amount (USD)</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>3326</td>
                                <td>10/21/2013</td>
                                <td>3:29 PM</td>
                                <td>$321.33</td>
                            </tr>
                            <tr>
                                <td>3325</td>
                                <td>10/21/2013</td>
                                <td>3:20 PM</td>
                                <td>$234.34</td>
                            </tr>
                            <tr>
                                <td>3324</td>
                                <td>10/21/2013</td>
                                <td>3:03 PM</td>
                                <td>$724.17</td>
                            </tr>
                            <tr>
                                <td>3323</td>
                                <td>10/21/2013</td>
                                <td>3:00 PM</td>
                                <td>$23.71</td>
                            </tr>
                            <tr>
                                <td>3322</td>
                                <td>10/21/2013</td>
                                <td>2:49 PM</td>
                                <td>$8345.23</td>
                            </tr>
                            <tr>
                                <td>3321</td>
                                <td>10/21/2013</td>
                                <td>2:23 PM</td>
                                <td>$245.12</td>
                            </tr>
                            <tr>
                                <td>3320</td>
                                <td>10/21/2013</td>
                                <td>2:15 PM</td>
                                <td>$5663.54</td>
                            </tr>
                            <tr>
                                <td>3319</td>
                                <td>10/21/2013</td>
                                <td>2:13 PM</td>
                                <td>$943.45</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="text-right">
                    <a href="#">View All Transactions <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.row -->

app/views/home/index.html.erb
<!DOCTYPE html>
<html>


    <head>

        <%= stylesheet_link_tag 'home' %>

    </head>

    <body>
      <div class="container">
        <div class="crop">
          <%= image_tag 'ioublue.png', class: 'logo' %>
        </div>
      </div>
      <div class="container">
        <h1 class="maintitle">THE BEST WAY TO SHARE EXPENSES BETWEEN FRIENDS.</h1>

      </div>
      <div class="container">
        <div class="signin">
          <%= link_to 'Sign In', new_user_session_path, class: "btn_in btn_main orange_btn main_btn" %>
        </div>&emsp;
        <div class="signup">
          <%= link_to 'Sign Up', new_user_registration_path, class: "btn_up btn_main red_btn main_btn" %>
        </div>
      </div>
    </body>
</html>

app/views/layouts/application.html.erb
<%= yield %>

app/views/layouts/createjoin.html.erb
<%= stylesheet_include_tag 'login' %>
<%= %= javascript_include_tag 'login' %>
<link rel="stylesheet" href="/assets/stylesheets/login.css">
<link href='http://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

<!-- Where all the magic happens -->
<!-- LOGIN FORM -->


<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <!-- Where all the magic happens -->
  <!-- LOGIN FORM -->
  <div class="text-center" style="text-align: center">
    <div class="logo">Create a group OR join one</div>
    <!-- Main Form -->
    <div class="login-form-1">
      <form id="register-form" class="text-left">
      <div class="login-form-main-message"></div>
      <div class="main-login-form">
        <div class="login-group">
          
          <button type="submit" class="createjoin"><%= render "devise/shared/links" %><i class="fa fa-chevron-right"></i></button>
          <button type="submit" class="createjoin"><%= render "devise/shared/links" %><i class="fa fa-chevron-right"></i></button>
       
        
      </div>
      
    </form>
    </div>
    <!-- end:Main Form -->
  </div>
<% end %>

app/views/layouts/home_template.html.erb
swag
<%= yield %>
swag

app/views/layouts/login.html.erb
<%= stylesheet_link_tag 'login' %>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

<%= yield %>

</div>

app/views/layouts/signup_template.html.erb
<%= stylesheet_include_tag 'signup' %>
<%= %= javascript_include_tag 'signup' %>
<link href='//cargocollective.com/hanken/HK-Grotesk-Open-Source-Font' rel='stylesheet' type='text/css'>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

<!-- Where all the magic happens -->
<!-- LOGIN FORM -->

<%=yield %>

app/views/payments/index.html.erb
<div class="row">
  <div class="col-md-6">
    <h1>Sent Payments <%= link_to 'Send money', new_payment_path(payment: {sender_id: current_user.id}), class: 'btn btn-primary btn-lg pull-right' %></h1>
    <table class="table">
      <thead>
        <tr>
          <th>To</th>
          <th>Amount</th>
          <th>Status</th>
          <th>Date</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @sent_payments.each do |payment| %>
        <tr>
          <td><%= payment.receiver.name %></td>
          <td><%= number_to_currency payment.amount %></td>
          <td><span class="label <%= label_status_class(payment.status) %>"><%= payment.status %></span></td>
          <td><%= payment.created_at.strftime("%B %d, %Y") %></td>
          <td><%= link_to 'View', payment, class: 'btn btn-default btn-sm' %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-md-6">
    <h1>Received Payments <%= link_to 'Get money', new_payment_path(payment: {receiver_id: current_user.id}), class: 'btn btn-primary btn-lg pull-right' %></h1>
    <table class="table">
      <thead>
        <tr>
          <th>From</th>
          <th>Amount</th>
          <th>Status</th>
          <th>Date</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @received_payments.each do |payment| %>
        <tr>
          <td><%= payment.sender.name %></td>
          <td><%= number_to_currency payment.amount %></td>
          <td><span class="label <%= label_status_class(payment.status) %>"><%= payment.status %></span></td>
          <td><%= payment.created_at.strftime("%B %d, %Y") %></td>
          <td><%= link_to 'View', payment, class: 'btn btn-default btn-sm' %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/payments/new.html.erb
<%= form_for(@payment) do |f| %>
  <div class="form-group">
    <%= render 'shared/error_messages', obj: @payment %>
  </div>
  <div class="form-group row">
    <div class="col-md-6">
      <%= f.label :sender %>
      <%= f.select :sender_id, User.all.map{|u| [u.name, u.id]}, {include_blank: "Choose"}, {class: 'form-control'} %>
    </div>
    <div class="col-md-6">
      <%= f.label :receiver %>
      <%= f.select :receiver_id, User.all.map{|u| [u.name, u.id]}, {include_blank: "Choose"}, {class: 'form-control'} %>
    </div>
    <div class="clearfix"></div>
  </div>
  <div class="form-group m-t-2">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control', placeholder: 'Payment for the groceries Feb. 29th' %>
  </div>
  <fieldset class="form-group m-t-2">
    <%= f.label :amount %>
    <div class="input-group">
      <div class="input-group-addon">$</div>
      <%= f.number_field :amount, class: 'form-control', step: '0.01', placeholder: '12.00' %>
    </div>
  </fieldset>
  <div class="form-group m-t-2">
    <%= f.label :due_date %>
    <%= f.date_field :due_date, class: 'form-control', placeholder: 'Payment for the groceries Feb. 29th' %>
  </div>
  <fieldset class="form-group">
    <%= f.submit 'Save payment', class: 'btn btn-primary' %>
  </fieldset>

<% end %>

app/views/payments/show.html.erb
<div class="row">
  <div class="col-md-8">
    <h1>
      <%= @payment.description %>&emsp;
      <span class="label <%= label_status_class(@payment.status) %>"><%= @payment.status %></span>
    </h1>
    <div class="row m-t-3">
      <div class="col-md-3"><h4>Total</h4></div>
      <div class="col-md-3">
        <div class="input-group">
          <div class="input-group-addon">$</div>
          <input type="text" class="form-control disabled" disabled value="<%= @payment.amount %>">
        </div>
      </div>
    </div>
    <div class="row m-t-3">
      <div class="col-md-3"><h4>Paid</h4></div>
      <div class="col-md-3">
        <div class="input-group">
          <div class="input-group-addon">$</div>
          <input type="text" class="form-control disabled" disabled value="<%= @payment.amount_paid %>">
        </div>
      </div>
    </div>
    <div class="row m-t-3">
      <div class="col-md-3"><h4>Owed</h4></div>
      <div class="col-md-3">
        <div class="input-group">
          <div class="input-group-addon">$</div>
          <input type="text" class="form-control disabled" disabled value="<%= @payment.amount_unpaid %>">
        </div>
      </div>
    </div>
    <div class="row m-t-2">
      <div class="col-md-3"><h4>Due</h4></div>
      <div class="col-md-9"><h4><%= @payment.due_date.strftime("%B %d, %Y") %></h4></div>
    </div>
    <% if current_user == @payment.sender && @payment.status != 'paid' %>
      <div class="row m-t-1">
        <div class="col-md-9 col-md-offset-3">
          <%= link_to new_payment_transfer_path(@payment), class: 'btn btn-lg btn-primary' do %>
          <i class="fa fa-money"></i> Pay
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <h2>History</h2>
    <ul>
      <% @payment.transfers.each do |transfer| %>
        <li style="list-style-type: none">
          <span class="badge"><%= transfer.created_at.strftime("%B %d, %Y") %></span>&nbsp;
          <h4 style="display: inline;"> Paid <%= number_to_currency transfer.amount %></h4>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger">
    <% obj.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
    <% end %>
  </div>
<% end %>

app/views/transfers/new.html.erb
<%= form_for([@payment, @transfer]) do |f| %>
  <div class="form-group">
    <%= render 'shared/error_messages', obj: @transfer %>
  </div>
  <div class="form-group row">
  <fieldset class="form-group m-t-2">
    <%= f.label :amount %>
    <div class="input-group">
      <div class="input-group-addon">$</div>
      <%= f.number_field :amount, class: 'form-control', step: '0.01', placeholder: '12.00', value: @payment.amount_unpaid %>
    </div>
  </fieldset>
  <div class="form-group m-t-2">
    <%= f.label :transfer_method %>
    <%= f.text_field :transfer_method, class: 'form-control', placeholder: 'cash', value: 'cash' %>
  </div>
  <fieldset class="form-group">
    <%= f.submit 'Save payment', class: 'btn btn-primary' %>
  </fieldset>

<% end %>